#!/bin/bash

echo
echo "Check the branch again"
echo "I know you think it is right"
echo "Check the branch again"
echo

echo -en "\033[31mAre you sure this is the right branch ಠಿ_ಠ? [y/N] \033[0m"
read -r answer </dev/tty

case "$answer" in
    y|Y|yes|YES)
        echo "Alright. Sending it."
        exit 0
        ;;
    *)
        echo "Push cancelled."
        exit 1
        ;;
esac
